import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef } from "react";
import Hls from "hls.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const audioRef = useRef<HTMLAudioElement>(null);
  useEffect(() => {
    const audio = audioRef.current;
    console.log(audio, Hls.isSupported());
    if (audio) {
      const hls = new Hls();
      if (Hls.isSupported()) {
        const streamUrl =
          (process.env.SERVER_URL ?? "") + "/hls/news" + "/output.m3u8"; // "https://streaming.radio.co/sd3b3d3e7e/listen";
        console.log(streamUrl);
        hls.loadSource(streamUrl);
        hls.on(Hls.Events.ERROR, (event, data) => {
          console.error("HLS error:", data);
        });

        hls.attachMedia(audio);
        hls.on(Hls.Events.MANIFEST_PARSED, () => {
          audio.play();
        });
      }
    }
  }, []);

  return (
    <>
      <Head>
        <title>Radio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <audio ref={audioRef} id="audio" controls></audio>
      </main>
    </>
  );
}
